name: "VS Code Tunnel"
description: "Download VS Code CLI and start a code tunnel"
author: "GitHub"

inputs:
  tunnel-name:
    description: "Name for the tunnel"
    required: false
  connection-timeout:
    description: "Connection timeout in minutes (default 2). If no connection is detected within this period the action will terminate the tunnel."
    required: false
    default: "2"
  session-timeout:
    description: "Session timeout in minutes (default 60). Starts after a connection is detected and will terminate the tunnel when reached."
    required: false
    default: "60"
outputs:
  tunnel-url:
    description: "The URL for accessing the tunnel"

runs:
  using: node20
  main: dist/action.js